from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_FotoPi(object):
    def setupUi(self, FotoPi):
        if not FotoPi.objectName():
            FotoPi.setObjectName(u"FotoPi")
        FotoPi.resize(1920, 1079)
        FotoPi.setMinimumSize(QSize(1280, 720))
        FotoPi.setMaximumSize(QSize(1920, 1080))
        FotoPi.setLayoutDirection(Qt.RightToLeft)
        FotoPi.setStyleSheet(u"background-color: rgb(34, 47, 62);")
        self.centralwidget = QWidget(FotoPi)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setLayoutDirection(Qt.RightToLeft)
        self.gridLayoutWidget_2 = QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(0, 0, 151, 1081))
        self.left_grid = QGridLayout(self.gridLayoutWidget_2)
        self.left_grid.setObjectName(u"left_grid")
        self.left_grid.setContentsMargins(0, 0, 0, 0)
        self.leftSpacer_2 = QSpacerItem(20, 850, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.left_grid.addItem(self.leftSpacer_2, 2, 0, 1, 1)

        self.leftSpacer_1 = QSpacerItem(20, 35, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.left_grid.addItem(self.leftSpacer_1, 0, 0, 1, 1)

        self.options_button = QPushButton(self.gridLayoutWidget_2)
        self.options_button.setObjectName(u"options_button")
        self.options_button.setMinimumSize(QSize(80, 80))
        self.options_button.setMaximumSize(QSize(80, 80))
        self.options_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.options_button.setFocusPolicy(Qt.NoFocus)
        icon = QIcon()
        icon.addFile(u"resources/icons/Settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.options_button.setIcon(icon)
        self.options_button.setIconSize(QSize(80, 80))
        self.options_button.setFlat(True)

        self.left_grid.addWidget(self.options_button, 1, 0, 1, 1)

        self.exit_button = QPushButton(self.gridLayoutWidget_2)
        self.exit_button.setObjectName(u"exit_button")
        self.exit_button.setMinimumSize(QSize(80, 80))
        self.exit_button.setMaximumSize(QSize(80, 80))
        self.exit_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.exit_button.setFocusPolicy(Qt.NoFocus)
        icon1 = QIcon()
        icon1.addFile(u"resources/icons/Exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.exit_button.setIcon(icon1)
        self.exit_button.setIconSize(QSize(80, 80))
        self.exit_button.setFlat(True)

        self.left_grid.addWidget(self.exit_button, 3, 0, 1, 1)

        self.leftSpacer_3 = QSpacerItem(20, 35, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.left_grid.addItem(self.leftSpacer_3, 4, 0, 1, 1)

        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(150, 0, 1450, 1082))
        self.viewport_grid = QHBoxLayout(self.horizontalLayoutWidget)
        self.viewport_grid.setObjectName(u"viewport_grid")
        self.viewport_grid.setContentsMargins(0, 0, 0, 0)
        # self.VIEWPORT = QLabel(self.horizontalLayoutWidget)
        # self.VIEWPORT.setObjectName(u"VIEWPORT")
        # self.VIEWPORT.setEnabled(True)
        # self.VIEWPORT.setMinimumSize(QSize(1440, 1080))
        # self.VIEWPORT.setMaximumSize(QSize(1440, 1080))
        # self.VIEWPORT.setPixmap(QPixmap(u"resources/dummy.png"))
        #
        # self.viewport_grid.addWidget(self.VIEWPORT)

        self.gridLayoutWidget_3 = QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(1600, 1020, 321, 61))
        self.right_grid_datetime = QGridLayout(self.gridLayoutWidget_3)
        self.right_grid_datetime.setObjectName(u"right_grid_datetime")
        self.right_grid_datetime.setHorizontalSpacing(6)
        self.right_grid_datetime.setVerticalSpacing(2)
        self.right_grid_datetime.setContentsMargins(0, 0, 0, 0)
        self.date_label = QLabel(self.gridLayoutWidget_3)
        self.date_label.setObjectName(u"date_label")
        self.date_label.setMinimumSize(QSize(0, 45))
        self.date_label.setMaximumSize(QSize(200, 45))
        font = QFont()
        font.setFamily(u"Continuum Medium")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("color: white;")
        self.date_label.setScaledContents(False)
        self.date_label.setAlignment(Qt.AlignVCenter|Qt.AlignHCenter)
        self.date_label.setWordWrap(False)
        self.date_label.setIndent(0)

        self.right_grid_datetime.addWidget(self.date_label, 2, 0, 1, 1)

        self.time_label = QLabel(self.gridLayoutWidget_3)
        self.time_label.setObjectName(u"time_label")
        self.time_label.setMinimumSize(QSize(0, 45))
        self.time_label.setMaximumSize(QSize(110, 45))
        QFontDatabase.addApplicationFont("fonts/contm.ttf")
        font1 = QFont()
        font1.setFamily(u"Continuum Medium")
        font1.setPointSize(26)
        font1.setBold(False)
        font1.setUnderline(False)
        font1.setWeight(50)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("color: white;")
        self.time_label.setAlignment(Qt.AlignVCenter|Qt.AlignHCenter)
        self.time_label.setMargin(0)
        self.time_label.setIndent(0)

        self.right_grid_datetime.addWidget(self.time_label, 2, 1, 1, 1)

        self.gridLayoutWidget_4 = QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setObjectName(u"gridLayoutWidget_4")
        self.gridLayoutWidget_4.setGeometry(QRect(1600, 460, 321, 162))
        self.right_grid_mid = QGridLayout(self.gridLayoutWidget_4)
        self.right_grid_mid.setObjectName(u"right_grid_mid")
        self.right_grid_mid.setContentsMargins(0, 0, 0, 0)
        self.capture_button = QPushButton(self.gridLayoutWidget_4)
        self.capture_button.setObjectName(u"capture_button")
        self.capture_button.setMinimumSize(QSize(160, 160))
        self.capture_button.setMaximumSize(QSize(160, 160))
        self.capture_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.capture_button.setFocusPolicy(Qt.NoFocus)
        self.capture_button.setLayoutDirection(Qt.RightToLeft)
        self.capture_button.setAutoFillBackground(False)
        icon2 = QIcon()
        icon2.addFile(u"resources/icons/Capture.png", QSize(), QIcon.Normal, QIcon.Off)
        self.capture_button.setIcon(icon2)
        self.capture_button.setIconSize(QSize(160, 160))
        self.capture_button.setFlat(True)

        self.right_grid_mid.addWidget(self.capture_button, 0, 0, 1, 1)

        self.gridLayoutWidget_7 = QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setObjectName(u"gridLayoutWidget_7")
        self.gridLayoutWidget_7.setGeometry(QRect(1600, 0, 321, 251))
        self.right_grid_top = QGridLayout(self.gridLayoutWidget_7)
        self.right_grid_top.setObjectName(u"right_grid_top")
        self.right_grid_top.setSizeConstraint(QLayout.SetMaximumSize)
        self.right_grid_top.setHorizontalSpacing(12)
        self.right_grid_top.setVerticalSpacing(24)
        self.right_grid_top.setContentsMargins(0, 24, 24, 0)
        self.iso_label = QLabel(self.gridLayoutWidget_7)
        self.iso_label.setObjectName(u"iso_label")
        self.iso_label.setMinimumSize(QSize(0, 0))
        self.iso_label.setMaximumSize(QSize(320, 80))
        font2 = QFont()
        font2.setFamily(u"Vegur")
        font2.setPointSize(34)
        font2.setBold(True)
        font2.setWeight(75)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferAntialias)
        self.iso_label.setFont(font2)
        self.iso_label.setLineWidth(0)
        self.iso_label.setScaledContents(False)
        self.iso_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.iso_label.setIndent(0)

        self.right_grid_top.addWidget(self.iso_label, 0, 1, 1, 1)

        self.iso_button = QPushButton(self.gridLayoutWidget_7)
        self.iso_button.setObjectName(u"iso_button")
        self.iso_button.setMinimumSize(QSize(0, 0))
        self.iso_button.setMaximumSize(QSize(80, 80))
        self.iso_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.iso_button.setFocusPolicy(Qt.NoFocus)
        self.iso_button.setLayoutDirection(Qt.RightToLeft)
        self.iso_button.setAutoFillBackground(False)
        icon3 = QIcon()
        icon3.addFile(u"resources/icons/ISO.png", QSize(), QIcon.Normal, QIcon.Off)
        self.iso_button.setIcon(icon3)
        self.iso_button.setIconSize(QSize(80, 80))
        self.iso_button.setFlat(True)

        self.right_grid_top.addWidget(self.iso_button, 0, 0, 1, 1)

        self.shutter_button = QPushButton(self.gridLayoutWidget_7)
        self.shutter_button.setObjectName(u"shutter_button")
        self.shutter_button.setMinimumSize(QSize(0, 0))
        self.shutter_button.setMaximumSize(QSize(80, 80))
        self.shutter_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.shutter_button.setFocusPolicy(Qt.NoFocus)
        self.shutter_button.setLayoutDirection(Qt.RightToLeft)
        self.shutter_button.setAutoFillBackground(False)
        icon4 = QIcon()
        icon4.addFile(u"resources/icons/ShutterSpeed.png", QSize(), QIcon.Normal, QIcon.Off)
        self.shutter_button.setIcon(icon4)
        self.shutter_button.setIconSize(QSize(80, 80))
        self.shutter_button.setFlat(True)

        self.right_grid_top.addWidget(self.shutter_button, 1, 0, 1, 1)

        self.shutter_label = QLabel(self.gridLayoutWidget_7)
        self.shutter_label.setObjectName(u"shutter_label")
        self.shutter_label.setMaximumSize(QSize(320, 80))
        self.shutter_label.setFont(font2)
        self.shutter_label.setAutoFillBackground(False)
        self.shutter_label.setLineWidth(0)
        self.shutter_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.shutter_label.setIndent(0)

        self.right_grid_top.addWidget(self.shutter_label, 1, 1, 1, 1)

        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(1800, 800, 123, 221))
        self.right_grid_bot = QGridLayout(self.gridLayoutWidget)
        self.right_grid_bot.setObjectName(u"right_grid_bot")
        self.right_grid_bot.setSizeConstraint(QLayout.SetMaximumSize)
        self.right_grid_bot.setHorizontalSpacing(12)
        self.right_grid_bot.setVerticalSpacing(24)
        self.right_grid_bot.setContentsMargins(17, 24, 24, 0)
        self.settings_button = QPushButton(self.gridLayoutWidget)
        self.settings_button.setObjectName(u"settings_button")
        self.settings_button.setMinimumSize(QSize(80, 80))
        self.settings_button.setMaximumSize(QSize(80, 80))
        self.settings_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.settings_button.setFocusPolicy(Qt.NoFocus)
        self.settings_button.setAutoFillBackground(False)
        icon5 = QIcon()
        icon5.addFile(u"resources/icons/Settings2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_button.setIcon(icon5)
        self.settings_button.setIconSize(QSize(80, 80))
        self.settings_button.setFlat(True)

        self.right_grid_bot.addWidget(self.settings_button, 1, 0, 1, 1)

        self.gallery_button = QPushButton(self.gridLayoutWidget)
        self.gallery_button.setObjectName(u"gallery_button")
        self.gallery_button.setMinimumSize(QSize(80, 80))
        self.gallery_button.setMaximumSize(QSize(80, 80))
        self.gallery_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.gallery_button.setFocusPolicy(Qt.NoFocus)
        self.gallery_button.setAutoFillBackground(False)
        icon6 = QIcon()
        icon6.addFile(u"resources/icons/Gallery.png", QSize(), QIcon.Normal, QIcon.Off)
        self.gallery_button.setIcon(icon6)
        self.gallery_button.setIconSize(QSize(80, 80))
        self.gallery_button.setFlat(True)

        self.right_grid_bot.addWidget(self.gallery_button, 0, 0, 1, 1)

        # FotoPi.setCentralWidget(self.centralwidget)

        self.retranslateUi(FotoPi)

        self.iso_button.setDefault(False)


        QMetaObject.connectSlotsByName(FotoPi)
    # setupUi

    def retranslateUi(self, FotoPi):
        FotoPi.setWindowTitle(QCoreApplication.translate("FotoPi", u"MainWindow", None))
        self.options_button.setText("")
        self.exit_button.setText("")
        #self.VIEWPORT.setText("")
        self.date_label.setText(QCoreApplication.translate("FotoPi", u"13.37.2077", None))
        self.time_label.setText(QCoreApplication.translate("FotoPi", u"08:09", None))
        self.capture_button.setText("")
        self.iso_label.setText("")
        self.iso_button.setText("")
        self.shutter_button.setText("")
        self.shutter_label.setText("")
        self.settings_button.setText("")
        self.gallery_button.setText("")
    # retranslateUi

